Fixes after review
Xceptance/neodymium-plugin-xcmailr pull request #1
Opened 2020-05-22 11:59 UTC by oomelianchuk

2020-05-28 07:42 UTC, ckeiner requested changes
* [ ] Don't set `null` to values if you don't need to. Not only does this allow to make this local variables `final`, you can then also often declare and set the value in the same line of code instead of spreading it across two or more lines.
* [ ] You often write `email` but the correct spelling is `e-mail`.

2020-05-28 07:42 UTC, ckeiner commented on config/xcmailr.properties
> +# URL to access both, the XcMailr server and web site
```suggestion
# URL to access the XcMailr server and web site
```

2020-05-28 07:42 UTC, ckeiner commented on config/xcmailr.properties
> +# Maximum waiting time for email to be received on the temporary e-mail address
```suggestion
# Maximum waiting time for the e-mail to be received on the temporary e-mail address
```

2020-05-28 07:42 UTC, ckeiner commented on config/xcmailr.properties
> +# How often the temporary mail should be checked for new e-mails
```suggestion
# Amount of time after which new e-mails are checked for
```

I'm not really satisfied with my suggestion either but I'd like to avoid question words to describe what a property does

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +     * option
```suggestion
     * Creates a temporary e-mail. <br>
     * The validity period is determined from the configuration.
```

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +     * test methods, which belong to one test class
```suggestion
     * Resets configuration properties for thread.<br>
     * This is required for unit tests to reset configurations for individual test methods of a single test class.
```

You can enforce a line break in your comments with `<br>`. 
In addition, Javadoc comments should be written in third person, see [Oracle's styleguide](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html#styleguide).

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +    protected static void resetConfigurationsForThread()
```suggestion
    static void resetConfigurationsForThread()
```

The default visibility modifier should be enough.

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +     *            varmail.international
```suggestion
     *            the e-mail address <br>
     *            The domain of the e-mail must match the XcMailr's available domains.
```

Our XcMailr does indeed only support those domains listed. Yet, a custom XcMailr can easily support other domains.

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +     * Get last received email with specified subject
```suggestion
     * Gets the last received e-mail with the specified subject.
```

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +     *            email address on which expected email should arrive
```suggestion
     *            the e-mail address which should receive the expected e-mail
```

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +     *            regular expression to find in the emails subject
```suggestion
     *            the received e-mail's subject. May also be a regular expression.
```

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +     * @return json object of received message
```suggestion
     * @return a String containing a JSON Object of the received message
```

However, if I take a look at the test, it seems as if we first get a JSON Array which then contains a JSON Object which contains our expected fields. Maybe we should describe this in our API Doc, too?

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +     * Get last received email from specified sender
```suggestion
     * Gets the last received e-mail from the specified sender.
```

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +     *            email address on which expected email should arrive
```suggestion
     *            the e-mail address which should receive the expected e-mail
```

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +     *            a regular expression to find in the address the mail was sent from
```suggestion
     *            the received e-mail's sender. May also be a regular expression.
```

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +     * @return json object of received message
```suggestion
     * @return a String containing a JSON Object of the received message
```

However, if I take a look at the test, it seems as if we first get a JSON Array which then contains a JSON Object which contains our expected fields. Maybe we should describe this in our API Doc, too?

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +     * @return object of the received message in format specified in parameters
```suggestion
    /**
     * Gets all received e-mails which match the specified parameters
     * 
     * @param email
     *            the e-mail address which should receive the expected e-mails.
     * @param from
     *            the received e-mail's sender. May also be a regular expression.
     * @param subject
     *           the received e-mail's subject. May also be a regular expression.
     * @param textContent
     *            the text content of the e-mail. May also be a regular expression.
     * @param htmlContent
     *            the HTML content of the e-mail. May also be a regular expression.
     * @param format
     *            a String indicating the desired response format. Valid values are "html", "json" and "header".
     * @param lastMatch
     *            a boolean indicating whether only the last e-mail or more should be returned.
     * @return a String containing JSON Objects of each e-mail
```

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +        Assert.assertEquals("Temporary Email could not be accessed", 200, response.code());
```suggestion
        Assert.assertEquals("Mailbox could not be accessed", 200, response.code());
```

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrHelper.java
> +     * Retrieve messages's text content from json response body
```suggestion
     * Retrieves the text content of the first e-mail from the JSON response body.
```

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrHelper.java
> +     * @param responseBody
Add a comment describing what the `responseBody` is

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrHelper.java
> +     * @return messages's text content
```suggestion
     * @return a String containing the e-mail's text content
```

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrHelper.java
> +     * @param responseBody
Add a comment describing what the `responseBody` is.

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrHelper.java
> +     * Retrieve messages's html content from json response body
```suggestion
     * Retrieves the HTML content of the first e-mail from the JSON response body.
```

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrHelper.java
> +     * @return messages's html content
```suggestion
     * @return a String containing the e-mail's html content
```

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrHelper.java
> +     * @param htmlContent
Add a comment describing what the `htmlContent` is.

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrHelper.java
> +     * Open passed html content in current browser window
```suggestion
     * Open the supplied HTML content with the current web driver.
```

2020-05-28 07:42 UTC, ckeiner commented on config/credentials.properties
> +SENDER_PORT = 25
Add comments what each property is

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/pageobjects/XcmailrOverviewPage.java
> +        tempEmails.findBy(exactText(email)).shouldBe(exist);
Use `should(exist)` to keep it fluent.

2020-05-28 07:42 UTC, ckeiner commented on config/credentials.properties
> +SENDER_PORT = 25
Remove port and add new line at the end of a file
```suggestion
SENDER_PORT =

```

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/pageobjects/XcmailrOverviewPage.java
>  public class XcmailrOverviewPage
This class doesn't seem to be used. Remove it.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/pageobjects/XcmailrLoginPage.java
>  {
This class doesn't seem to be used. Remove it.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/XcMailrApiTest.java
>      @Before
The more I look at the method, the more it seems that this should rather be done in a `BeforeClass` step as you simply set static values.
Please take a look whether or not you can do this actually.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/XcMailrApiTest.java
> -@Browser("Chrome_headless")
Since you don't need a browser anymore, you should be able to remove most property files

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendEmail.java
> +            e.printStackTrace();
The method should throw the `MessagingException` instead of simply printing the stack trace so we know that sending an e-mail failed instead of "silently" ignoring it.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendRequest.java
> +            String output = br.readLine();
While this does indeed solve the error we had previously, `br` can still be `null` if the `httpClient.execute` method failed.
Hence, you should add a null check to the `br.close` in line 98.

However, why do we only close the `BufferedReader` when an exception is thrown?

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendRequest.java
>              }
You do not do anything with the reader and resulting string. Hence, you should remove it.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/XcMailrApiTest.java
> +    protected final String xcmailrPassword = CREDENTIALS.xcmailrPassword();
There is no need to set both of these as members of the class, especially since you only require each once.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/XcMailrApiTest.java
> +    protected final String tempEmail = "testTest1@varmail.net";
This mail causes me to always receive a `forbidden`. Add some random alphanumeric characters to the local part of the email to avoid this.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/XcMailrApiTest.java
> +        writeProperty("xcmailr.temporaryMailValidMinutes", "3");
Previously, you wrote both properties to the map and then wrote it to the configuration file. Now, you write to the config file twice.
The former method makes more sense, so you should add the former again.

2020-05-28 07:42 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +    protected static void resetConfigurationsForThread()
However, I do not believe you should add methods to the API simply for the sake of testing. Especially, since this isn't even needed if you simply use 1 minute for all your API tests.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/XcMailrApiTest.java
> +        writeProperty("xcmailr.temporaryMailValidMinutes", "1");
Why do you not set this for all your tests here? Each test should be able to deal with a one minute validity.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/XcMailrApiTest.java
> +    private String decode(String text)
Since you do not only decode, add a comment what this method does and maybe rename it to `decodeAndNormalize` or something similar.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/XcMailrApiTest.java
> +}
Add a newline at the end of the file

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/XcMailrApiTest.java
> +    protected static final Credentials CREDENTIALS = ConfigFactory.create(Credentials.class, System.getenv());
IMO, static members should always be the first member's of the class, followed by the non-static ones. This holds especially since other members rely on this static one.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/XcMailrHelperTest.java
>  public class XcMailrHelperTest extends AbstractTest
This class doesn't need to inherit from `AbstractTest`.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/AbstractTest.java
> +        XcMailrApi.resetConfigurationsForThread();
This isn't needed if your properties stay the same in each test class which is definitely possible.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendRequest.java
> +    private static CloseableHttpClient httpClient = HttpClientBuilder.create().build();
This may create a `peer not authorized` exception. Please look into why this is thrown but not with the `DefaultHttpClient`.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendRequest.java
>          HttpResponse response = null;
There is no need to force this to `null`. Simply declare it.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendRequest.java
>          BufferedReader br = null;
There is no need to force this to `null`. Simply declare it.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendRequest.java
> +            String output = br.readLine();
While this does indeed solve the error we had previously, `br` can still be `null` if the `httpClient.execute` method failed.
Hence, you should add a null check to the `br.close` in line 62.

However, why do we only close the `BufferedReader` when an exception is thrown?

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendRequest.java
>              e.printStackTrace();
We throw the exception already, no need to print the stack trace.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendRequest.java
>          }
We throw the exception in line 69 already, so there is no need to print the stack trace in line 68.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendRequest.java
> +            String output = br.readLine();
While this does indeed solve the error we had previously, `br` can still be `null` if the `httpClient.execute` method failed.
Hence, you should add a null check to the `br.close` in line 150.

However, why do we only close the `BufferedReader` when an exception is thrown?

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendRequest.java
> +                output = br.readLine();
You don't use what you read so why do you read it at all?

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendRequest.java
>              throw new RuntimeException(e);
We throw the exception already, no need to print the stack trace before.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendRequest.java
> +}
Add a new line at the end of the file.

2020-05-28 07:42 UTC, ckeiner commented on config/credentials.properties
> +SENDER_PORT = 25
Add a new line at the end of the file.

2020-05-28 07:42 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendRequest.java
Don't declare variables in a line and then set a value right after. Just do both in a singe line, e.g.
```
HttpResponse  = httpClient.execute(postRequest);
```

2020-05-28 07:46 UTC, ckeiner commented on src/test/java/util/xcmailr/XcMailrApiTest.java
> +        Selenide.sleep(120000);
Add a note saying that the job for deleting e-mails only runs every minute so we have to wait 2 minutes to work reliably.

2020-06-10 09:02 UTC, ckeiner requested changes
* Run the formatter on the project to fix formatting issues.
* The base URL of XcMailr may not end with `/` as this is optional. Hence, you should use `StringUtils.appendIfMissing` to append a slash if it is missing

2020-06-10 09:02 UTC, ckeiner commented on config/credentials.properties
> +SENDER_PORT =
* Stick with proper spelling in the comments, e.g. "XcMailr" instead of "xcmail", "e-mail" instead of "email"
* Start the comment capitalized as this is done in the neodymium-library as well
* Give proper names to the properties, e.g. why is `EMAIL_LOGIN` not `SMTP_LOGIN` when it is the login for the SMTP server and not for some e-mail?

2020-06-10 09:02 UTC, ckeiner commented on config/xcmailr.properties
> +# Period during which the created temporary email should be active
```suggestion
# Period during which the created temporary e-mail should be active
```

2020-06-10 09:02 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrHelper.java
> +     * Retrieves the text content of the first e-mail from the JSON response body. *
```suggestion
     * Retrieves the text content of the first e-mail from the JSON response body.
```

2020-06-10 09:02 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrHelper.java
> +     *            is the return value of XcMailApi.fetchEmails() and its sugar methods
Generally, the Javadoc comment of a parameter starts with the type of the parameter and then describe what it is. It should also not be too technical, e.g.

```suggestion
     *            a String containing the response of an XcMailr API call, e.g. <code>XcMailrApi.fetchEmails</copde>
```

2020-06-10 09:02 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrHelper.java
> +     *            is the return value of XcMailApi.fetchEmails() and its sugar methods
```suggestion
     *            a String containing the response of an XcMailr API call, e.g. <code>XcMailrApi.fetchEmails</copde>
```

2020-06-10 09:02 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrHelper.java
> +     *            is any HTML text, e.g. return value of the getFirstMailsHtmlContent() method
```suggestion
     *            a String containing the HTML that should be opened in the current web driver
```

2020-06-10 09:02 UTC, ckeiner commented on src/test/java/util/xcmailr/pageobjects/XcmailrOverviewPage.java
>  public class XcmailrOverviewPage
Why isn't it removed?

2020-06-10 09:02 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendEmail.java
> +            throw new RuntimeException("failed to send email via smtp server", e);
```suggestion
            throw new RuntimeException("Failed to send e-mail via SMTP server", e);
```

2020-06-10 09:02 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +        Assert.assertEquals("Temporary Email could not be accessed", 200, response.code());
We really create a temporary e-mail address here.
```suggestion
        Assert.assertEquals("Temporary Email could not be created", 200, response.code());
```

2020-06-10 09:02 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +    private static String retrieveLastEmail(String email, String sender, String subject)
While I did say that we actually get a JSON Array of a single JSON object, that doesn't mean you should parse the response. Instead, be exact in your wording of the return value, e.g. "a String containing XCMailr's response" and maybe even give an example in the class comment.
Remove this method.

2020-06-10 09:02 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +        String responseBody = readResponse(response.body().byteStream()).toString();
I don't understand why you need to read the response when we can call `response.body().string()` like we do in `fetchEmails`. Please explain what the difference here is.

2020-06-10 09:02 UTC, ckeiner commented on src/test/java/util/xcmailr/AbstractTest.java
> +                                                        tempFile.getAbsoluteFile(), e));
```suggestion
                System.out.println(MessageFormat.format("Couldn''t delete temporary file: ''{0}'' caused by {1}",
                                                        tempFile.getAbsoluteFile(), e));
```
Spelling & Formatting

2020-06-10 09:02 UTC, ckeiner commented on src/test/java/util/xcmailr/XcMailrApiTest.java
> +        final String xcmailrPassword = CREDENTIALS.xcmailrPassword();
Put these arguments directly in the `SendRequest.login` call instead of allocating local variables

2020-06-10 09:02 UTC, ckeiner commented on src/test/java/util/xcmailr/AbstractTest.java
> +    protected static void writeProperty()
To avoid confusion, rather call this method `writeProperties` since you write multiple properties and not just one.

2020-06-10 09:02 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendEmail.java
> +     * Method to send message
1. Stick with the guidelines of Oracle's [style guide](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html#styleguide)
 > Method descriptions begin with a verb phrase
2. Be more specific. We send an e-mail, not just any message.

```suggestion
     * Sends an e-mail from the specified <code>emailAccount</code> to the specified <code>recipient</code>.
```

2020-06-10 09:02 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendEmail.java
> +     *            message text
Fix parameters

2020-06-10 09:02 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendRequest.java
> +    private static CloseableHttpClient httpClient = HttpClientBuilder.create().build();
Now, the `DefaultHttpClient` also throws the `peer not authorized` exception

2020-06-10 09:02 UTC, ckeiner commented on config/neodymium.properties
> +neodymium.dataUtilsEmailDomain = varmail.net
I talked with @occupant23 about this and we think that we may not even need Neodymium in this project at all since everything should work without Neodymium. This also avoids us having to have properties just for testing.

2020-06-10 09:02 UTC, ckeiner commented on config/credentials.properties
> +SENDER_PORT =
Make this a template, which you commit and remove this properties file.
Then comment every line.
Also find a better fitting name.

2020-06-10 09:02 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrHelper.java
> +        final JsonObject emailObject = tempJsonElement.getAsJsonObject();
Why did you remove the safety checks?

2020-06-10 13:50 UTC, oomelianchuk commented on src/test/java/util/xcmailr/pageobjects/XcmailrOverviewPage.java
>  public class XcmailrOverviewPage
this import statement cannot be removed because it's the return type of the findStatus(String email) method

2020-06-15 12:37 UTC, ckeiner requested changes

2020-06-15 12:37 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendEmail.java
> +     *            is an <code>EmailAccount</code> object containing configuration of SMTP server and credentials for it
Good step annotation. The only improvement here is to leave out the verb and link to the emailAccount as this is its first occurrence in the class, hence:
`an {@link EmailAccount} ...`

2020-06-15 12:37 UTC, ckeiner commented on src/test/java/util/xcmailr/pageobjects/XcmailrOverviewPage.java
>  public class XcmailrOverviewPage
I mean the class or rather the whole package.

2020-06-15 12:37 UTC, ckeiner commented on config/credentials.properties.templates
> +SMTP_SERVER_HOST=
```suggestion
SMTP_SERVER_HOST = 
```
missing space

2020-06-15 12:37 UTC, ckeiner commented on pom.xml
> +			<version>${neodymium.version}</version> </dependency> -->
Don't comment it out, just remove it.
```suggestion
```

2020-06-15 12:37 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +     * @throws IOException
JavaDoc is missing `@return`

2020-06-15 12:37 UTC, ckeiner commented on src/test/java/util/xcmailr/AbstractTest.java
> +    protected static void writeProperties()
Maybe we should rather rename this method to `savePropertiesAndApply`? What do you think?

2020-06-15 12:37 UTC, ckeiner commented on src/test/java/util/xcmailr/XcMailrApiTest.java
> +    private static String randomEmail(String prefix, String domian)
Typo. It's domain.

2020-06-15 12:37 UTC, ckeiner commented on pom.xml
> +			<artifactId>allure-junit4</artifactId>
IMO, we don't need Allure in this project. I don't think its even really used. So we should remove it with all dependencies.

2020-06-15 12:37 UTC, ckeiner commented on pom.xml
> +		</dependency>
As far as I can see, you only require:
* javax.mail
* junit
* owner
* httpclient
* selenide
* json-path

Please verify and remove the unnecessary dependencies.

2020-06-15 12:37 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendRequest.java
>                  br.close();
If we cannot create the buffered reader, this throws a NPE. Please only close it if br is not null.

2020-06-16 08:52 UTC, ckeiner requested changes

2020-06-16 08:52 UTC, ckeiner commented on pom.xml
>  								<include>util.xcmailr/**/*Test.java
This should be
```suggestion
								<include>util/xcmailr/**/*Test.java
```

2020-06-16 08:52 UTC, ckeiner commented on src/main/java/util/xcmailr/XcMailrApi.java
> +     * @return server response with information about the temporary e-mail
```suggestion
     * @return a String containing the server's response with information about the temporary e-mail
```

2020-06-16 08:52 UTC, ckeiner commented on src/test/java/util/xcmailr/util/SendEmail.java
> +     *            is an {@link EmailAccount} object with configuration of SMTP server and credentials for it
```suggestion
     *            an {@link EmailAccount} object with configuration of SMTP server and credentials for it
```

2020-06-16 08:56 UTC, ckeiner commented
I also just noticed that the "pageobjects" package is still in the project. Please remove it, too.

2020-06-16 09:02 UTC, ckeiner approved these changes

2020-06-16 09:03 UTC, merged